language: cpp
compiler:
  - gcc
  - clang

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3

script: >
    ./waf configure --enable-test &&
    ./waf build &&
    build/test/f3kdb-test --gtest_filter='-Core/*' &&
    build/test/f3kdb-test --gtest_filter='Core/*/?:Core/*/??' &&
    build/test/f3kdb-test --gtest_filter='Core/*/?4?:Core/*/?7?' &&
    build/test/f3kdb-test --gtest_filter='Core/*/??3?:Core/*/??6?'
