language: cpp
compiler:
  - gcc
  - clang

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script: >
    ./waf configure --enable-test &&
    ./waf build &&
    build/test/f3kdb-test --gtest_filter='-Core/*' &&
    build/test/f3kdb-test --gtest_filter='Core/*/?:Core/*/??' &&
    build/test/f3kdb-test --gtest_filter='Core/*/?4?:Core/*/?7?' &&
    build/test/f3kdb-test --gtest_filter='Core/*/??3?:Core/*/??6?'
